"""add upload_history validation_summary

Revision ID: 03615d8ff432
Revises: a1155e236d0e
Create Date: 2026-08-27 10:16:04.848360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03615d8ff432'
down_revision: Union[str, Sequence[str], None] = 'a1155e236d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_summary', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.drop_column('validation_summary')

    # ### end Alembic commands ###
