"""add upload_history processed_file_path and eda_results

Revision ID: f0a157240356
Revises: bc0308897a9b
Create Date: 2026-08-27 02:45:00.613194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a157240356'
down_revision: Union[str, Sequence[str], None] = 'bc0308897a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('eda_results', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_history', schema=None) as batch_op:
        batch_op.drop_column('eda_results')
        batch_op.drop_column('processed_file_path')

    # ### end Alembic commands ###
